version: "3"
services:
  app:
    image: fiber-go-exercise:latest
    depends_on:
      - postgres
    networks:
      - resource-network
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
      - DB_NAME=test
      - DB_PORT=5432
      - PORT=8080
    ports:
      - "8080:8080"
    restart: always
  postgres:
    image: postgres:12-alpine
    networks:
      - resource-network
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
      - my-db:/var/lib/postgresql/data
networks:
    resource-network:
      driver: bridge
volumes:
  my-db: